// React/lab1/slideshow/src/components/lab2/table.js
function Table({ list }) {
  const row = list.map((item) => (
    <tr>
      <td>{item.name}</td>
      <td>{item.age}</td>
    </tr>
  ));
  return (
    <div className="container mx-auto mt-4">
      <table className="table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
          </tr>
        </thead>
        <tbody>{row}</tbody>
      </table>
    </div>
  );
}

export default Table;

// Angular/lab3/table/src/app/components/lab4/table/table.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css'],
})
export class TableComponent {
  @Input() list: { name: string; age: number }[] = [];
}

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let student of list; index as i">
        <td>{{ i + 1 }}</td>
        <td>{{ student.name }}</td>
        <td>{{ student.age }}</td>
      </tr>
    </tbody>
  </table>
</div>
