// Angular/lab6/src/app/components/user-details/user-details.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { UsersService } from 'src/app/services/users.service';

@Component({
  selector: 'app-user-details',
  templateUrl: './user-details.component.html',
  styleUrls: ['./user-details.component.css'],
})
export class UserDetailsComponent implements OnInit, OnDestroy {
  id: any;
  eve: any;
  user: any;
  
  constructor(
    private api: UsersService,
    current_id: ActivatedRoute,
    private router: Router
  ) {
    this.id = current_id.snapshot.params.id;
  }

  ngOnInit(): void {
    this.eve = this.api.get_user(this.id).subscribe(
      (response) => {
        this.user = response.body;
      },
      (err) => {
        console.log(err);
      }
    );
  }

  ngOnDestroy(): void {
    this.eve.unsubscribe();
  }

  delete_user() {
    const ans = confirm('Are you sure?');
    if (ans) {
      this.api.delete_user(this.id).subscribe();
      this.router.navigateByUrl('users');
    }
  }

  edit_user_info(id: any) {
    this.router.navigateByUrl(`users/edit/${id}`);
  }
}

<div class="container">
  <div class="card m-3" style="width: 25rem" *ngIf="user; else noData">
    <div class="card-body">
      <h5 class="card-title">Name: {{ user.name }}</h5>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Email: {{ user.email }}</li>
      <li class="list-group-item">Phone: {{ user.phone }}</li>
    </ul>
    <div class="card-body">
      <input
        type="button"
        value="Edit"
        class="btn btn-primary m-2"
        (click)="edit_user_info(user.id)"
      />
      <input
        type="button"
        value="Delete"
        class="btn btn-danger m-2"
        (click)="delete_user()"
      />
    </div>
  </div>
</div>
<ng-template #noData>
  <div class="spinner-border text-primary text-center" role="status"></div>
</ng-template>

// React/lab5/frontend/src/components/user/user_details.jsx
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import user_details from "../../actions/user_details";
import clear_details from "../../actions/clear_details";
import delete_user from "../../actions/delete_user";

export default function User_details(props) {
  const id = props.match.params.id;
  const dispatch = useDispatch();
  const user = useSelector((state) => state.users.details);

  useEffect(() => {
    dispatch(user_details(id));
    dispatch(clear_details());
  }, [dispatch, id]);

  const userUi = (user) => {
    console.log(user);
    if (user != null) {
      if (user.length === 0)
        return <div className="text-center fs-2  m-5">Not found</div>;
      return (
        <div className="container ">
          <div className="card mt-5">
            <div className="row g-0">
              <div className="col-md-6 col-xl-4">
                <img
                  src={`http://localhost:3001${user.image}`}
                  className="img-fluid rounded-start"
                  alt={user.name}
                />
              </div>
              <div className="col-md-6">
                <div className="card-body">
                  <h5 className="card-title">Name: {user.name}</h5>
                  <p className="card-text">Email: {user.email}</p>
                  <div className="">
                    <input
                      type="button"
                      value="Edit"
                      className="btn btn-primary ml-0 mr-2 mt-2 mb-2"
                    />
                    <input
                      type="button"
                      value="Delete"
                      className="btn btn-danger m-2"
                      onClick={() => {
                        const ans = window.confirm("Are you Sure?");
                        if (ans) {
                          dispatch(delete_user(id));
                          props.history.replace("/");
                        }
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      );
    }
    return (
      <div className="d-flex justify-content-center m-5">
        <div className="spinner-border text-info" role="status"></div>
      </div>
    );
  };

  return userUi(user);
}
